// AUTO-GENERATED by scripts--i18n_apply (Chantan).
// Regenerated on every i18n_apply run. Manual edits to this file get
// overwritten — to customize, ask the AI to "make the language toggle
// <your change>" and the regen will incorporate it.

import { useTranslation } from "react-i18next"
import type { ChangeEvent } from "react"

const LABELS: Record<string, { short: string; native: string }> = {
  "en": { short: "EN", native: "English" },
  "ar": { short: "ع", native: "العربية" },
  "fr": { short: "FR", native: "Français" }
}

const ORDER = ["en","ar","fr"]

export function LanguageToggle() {
  const { i18n } = useTranslation()
  const current = ORDER.includes(i18n.language) ? i18n.language : ORDER[0]

  return (
    <select
      value={current}
      onChange={(e: ChangeEvent<HTMLSelectElement>) => i18n.changeLanguage(e.target.value)}
      className="text-sm font-medium px-3 py-1.5 rounded-full border border-border bg-background text-foreground hover:bg-accent transition-colors cursor-pointer focus:outline-none focus:ring-2 focus:ring-ring"
      aria-label="Select language"
    >
      {ORDER.map(code => (
        <option key={code} value={code}>
          {LABELS[code]?.native || code.toUpperCase()}
        </option>
      ))}
    </select>
  )
}
